name: Mejorar mensajes de commit

on:
  push:
    branches:
      - main

jobs:
  improve_commit_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Mejorar mensajes de commit
        run: |
          git fetch --prune
          git rebase origin/main  # Asegura que estamos trabajando sobre la rama principal
          git log --pretty=format:'%h %s' | while read hash message; do
            # Aplicar reglas para mejorar la coherencia de los mensajes de commit
            new_message=$(echo "$message" | sed 's/typo1/typo2/g')  # Ejemplo: corregir errores tipográficos
            new_message=$(echo "$new_message" | sed 's/fix1/fix2/g')  # Ejemplo: cambiar 'fix1' por 'fix2'
            new_message=$(echo "$new_message" | sed 's/feature1/feature2/g')  # Ejemplo: cambiar 'feature1' por 'feature2'
            # Agregar más reglas según sea necesario

            git commit --amend -m "$new_message" $hash
          done
          git push --force-with-lease origin main  # Usar force push con precaución
