version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps)"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
    labels:
    - "Dependencias del Devcontainer"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "mamasita"
    labels:
    - "Dependencias del actions"
