name: Actualizar sistema Linux

on:
  schedule:
    - cron: "0 0 * * *" # Ejecutar diariamente a medianoche

jobs:
  update_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Actualizar paquetes del sistema
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
