- params:
    git:
      repoName: Proyecto1Marcas
      branches:
        - main
    scan:
      emailReceivers:
        - sbuendiaisrael@gmail.com
      projects:
        - workingDirs:
            - action
        - workingDirs:
            - .
