name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1.11.0
              with:
                  assignees: IsraC0d33,MarcosAcedoLlerena,MarioGalanEscudero,roberto-ortizperez,MuiGt
                  numOfAssignee: 1
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
