name: codespell
on: [push, pull_request]
permissions: {}
jobs:
  codespell:
    name: Verificar errores de ortografía
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          args: --language=es
