name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *' # Ejecuta el trabajo todos los días a la 1:30 UTC
 
jobs:
  stale:
    runs-on: ubuntu-latest # Ejecuta una máquina virtual Ubuntu con la última versión disponible
    steps:
      - uses: actions/stale@v9 # Utiliza stale para cerrar temas y PRs obsoletos
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} # Utiliza el token de github para autenticar la acción
          stale-issue-message: 'Este tema está obsoleto porque lleva abierto 2 días sin actividad. Elimina la etiqueta o el comentario o se cerrará en 3 días.' # Especifica el mensaje a mostrar en los temas obsoletos
          stale-pr-message: 'Este PR está obsoleto porque lleva abierto 5 días sin actividad. Elimine la etiqueta de obsoleto o coméntelo o se cerrará en 10 días.' # Especifica el mensaje a mostrar en los pull request obsoletos
          close-issue-message: 'Este tema se ha cerrado porque lleva 5 días parado sin actividad.' # Especifica el mensaje a mostrar al cerrar un tema obsoleto
          exempt-all-issue-assignees: true # no cierra una incidencia si se le ha asignado a alguien.
          close-pr-message: 'Este PR se cerró porque lleva 10 días estancado sin actividad.' # Especifica el mensaje a mostrar al cerrar un pull request obsoleto
          exempt-all-pr-assignees: true # no cierra un pr si alguien fue asignado a él.
          days-before-issue-stale: 2  # Número de días antes de que un tema se considere obsoleto
          days-before-pr-stale: 5  # Número de días antes de que una pull reques se considere obsoleto
          days-before-issue-close: 3 # Número de días antes de cerrar un tema obsoleto
          days-before-pr-close: 10 # Número de días antes de cerrar un pull reques obsoleto
