name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '41 10 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-close: 1
          close-issue-message: 'Esta issue se a cerrado por que no ha habido actividad durante 1 dia'
          exempt-all-pr-assignees: true
          enable-statistics: true
          debug-only: true
